version: 2
updates:
  # Scan for Docker updates in Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Scan for PHP dependencies
  - package-ecosystem: "composer"
    directory: "/src"
    schedule:
      interval: "weekly"

  # Include GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
