name: Build and Push Docker Image

# Trigger on release events and manually via workflow_dispatch
on:
  release:
    types: [created]
  push:
    branches:
      - feature/dockerhub-workflow-#1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub (Dry Run)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Commenting out this step since login doesn’t have a dry-run option, but login is required for further steps.

      - name: Set version-date tag
        id: tag
        run: |
          VERSION=${{ github.event.release.tag_name || 'v0.0.0' }}
          DATE_TAG=$(date +'%Y%m%d')
          VERSION_TAG="${VERSION}-${DATE_TAG}"
          echo "::set-output name=tag::${VERSION_TAG}"
      
      - name: Build Docker image (Dry Run)
        run: |
          echo "Dry run build command: docker build -t maboni82/external-ip-checker:latest -t maboni82/external-ip-checker:${{ steps.tag.outputs.tag }} ."
          # Actual build command, commented out
          # docker build -t maboni82/external-ip-checker:latest -t maboni82/external-ip-checker:${{ steps.tag.outputs.tag }} .

      - name: Push Docker images to Docker Hub (Dry Run)
        run: |
          echo "Dry run push command: docker push maboni82/external-ip-checker:latest"
          echo "Dry run push command: docker push maboni82/external-ip-checker:${{ steps.tag.outputs.tag }}"
          # Actual push commands, commented out
          # docker push maboni82/external-ip-checker:latest
          # docker push maboni82/external-ip-checker:${{ steps.tag.outputs.tag }}