name: Build and Push Docker Image

# Trigger the workflow on release events
on:
#  release:
#    types: [created]
    push:
      branches:
        - feature/dockerhub-workflow-#1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version-date tag
        id: tag
        run: |
          VERSION=${{ github.event.release.tag_name }}
          DATE_TAG=$(date +'%Y%m%d')
          VERSION_TAG="${VERSION}-${DATE_TAG}"
          echo "tag=$VERSION_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t maboni82/external-ip-checker:latest \
                       -t maboni82/external-ip-checker:${{ env.tag }} .

      - name: Push Docker images to Docker Hub
        run: |
          docker push maboni82/external-ip-checker:latest
          docker push maboni82/external-ip-checker:${{ env.tag }}